chore: Restructure ssh setup and playbooks
Signed-off-by: Klaus Smolin <smolin@de.ibm.com>

diff --git a/playbooks/reinstall_cluster.yaml b/playbooks/reinstall_cluster.yaml
--- a/playbooks/reinstall_cluster.yaml
+++ b/playbooks/reinstall_cluster.yaml
@@ -6,114 +6,112 @@
   hosts: localhost
   tags: ssh, ssh_copy_id, section_1
   gather_facts: true
-  vars:
-    ssh_target:
-      [
-        "{{ env.bastion.networking.ip }}",
-        "{{ env.bastion.access.user }}",
-        "{{ env.bastion.access.pass }}",
-        "{{ path_to_key_pair }}",
-      ]
   roles:
-    - ssh_copy_id
+    - role: ssh_copy_id_v2
+      vars:
+        parm_host:
+          ip: "{{ env.bastion.networking.ip }}"
+          user: "{{ env.bastion.access.user }}"
+          pass: "{{ env.bastion.access.pass }}"
+        parm_ssh_key_path: "{{ env_ssh_key_path }}"
 
-- name: Re-Install cluster - Copy SSH key to access KVM host 1
-  hosts: localhost
-  tags: ssh, ssh_copy_id, section_1, kvm_host_1
-  connection: local
-  become: false
-  gather_facts: true
-  vars:
-    ssh_target:
-      [
-        "{{ env.systems.host1.ip }}",
-        "{{ env.systems.host1.user }}",
-        "{{ env.systems.host1.pass }}",
-        "{{ path_to_key_pair }}",
-      ]
-  tasks:
-    - name: Include vars for the KVM host
-      ansible.builtin.include_vars:
-        file: "{{ inventory_dir }}/host_vars/{{ env.systems.host1.hostname }}.yaml"
+# - name: Re-Install cluster - Copy SSH key to access KVM host 1
+#   hosts: localhost
+#   tags: ssh, ssh_copy_id, section_1, kvm_host_1
+#   connection: local
+#   become: false
+#   gather_facts: true
+#   vars:
+#     ssh_target:
+#       [
+#         "{{ env.systems.host1.ip }}",
+#         "{{ env.systems.host1.user }}",
+#         "{{ env.systems.host1.pass }}",
+#         "{{ path_to_key_pair }}",
+#       ]
+#   tasks:
+#     - name: Include vars for the KVM host
+#       ansible.builtin.include_vars:
+#         file: "{{ inventory_dir }}/host_vars/{{ env.systems.host1.hostname }}.yaml"
 
-    - name: Copy SSH key to KVM host
-      ansible.builtin.import_role:
-        name: ssh_copy_id
+#     - name: Copy SSH key to KVM host
+#       ansible.builtin.import_role:
+#         name: ssh_copy_id
 
-- name: Re-Install cluster - Copy SSH key to access KVM host 2
-  hosts: localhost
-  tags: ssh, ssh_copy_id, section_1, kvm_host_2
-  connection: local
-  become: false
-  gather_facts: false
-  vars:
-    ssh_target:
-      [
-        "{{ env.systems.host2.ip }}",
-        "{{ env.systems.host2.user }}",
-        "{{ env.systems.host2.pass }}",
-        "{{ path_to_key_pair }}",
-      ]
-  tasks:
-    - name: Include vars for second KVM host
-      ansible.builtin.include_vars:
-        file: "{{ inventory_dir }}/host_vars/{{ env.systems.host2.hostname }}.yaml"
-      when: env.systems.host2.hostname is defined
+# - name: Re-Install cluster - Copy SSH key to access KVM host 2
+#   hosts: localhost
+#   tags: ssh, ssh_copy_id, section_1, kvm_host_2
+#   connection: local
+#   become: false
+#   gather_facts: false
+#   vars:
+#     ssh_target:
+#       [
+#         "{{ env.systems.host2.ip }}",
+#         "{{ env.systems.host2.user }}",
+#         "{{ env.systems.host2.pass }}",
+#         "{{ path_to_key_pair }}",
+#       ]
+#   tasks:
+#     - name: Include vars for second KVM host
+#       ansible.builtin.include_vars:
+#         file: "{{ inventory_dir }}/host_vars/{{ env.systems.host2.hostname }}.yaml"
+#       when: env.systems.host2.hostname is defined
 
-    - name: copy SSH key to second KVM host, if cluster is to be highly available
-      ansible.builtin.import_role:
-        name: ssh_copy_id
-      when: env.systems.host2.hostname is defined
+#     - name: copy SSH key to second KVM host, if cluster is to be highly available
+#       ansible.builtin.import_role:
+#         name: ssh_copy_id
+#       when: env.systems.host2.hostname is defined
 
-- name: Re-Install cluster - Copy SSH key to access KVM host 3
-  hosts: localhost
-  tags: ssh, ssh_copy_id, section_1, kvm_host_3
-  connection: local
-  become: false
-  gather_facts: false
-  vars:
-    ssh_target:
-      [
-        " {{ env.systems.host3.ip }}",
-        "{{ env.systems.host3.user }}",
-        "{{ env.systems.host3.pass }}",
-        "{{ path_to_key_pair }}",
-      ]
-  tasks:
-    - name: Include vars for third KVM host
-      ansible.builtin.include_vars:
-        file: "{{ inventory_dir }}/host_vars/{{ env.systems.host3.hostname }}.yaml"
-      when: env.systems.host3.hostname is defined
+# - name: Re-Install cluster - Copy SSH key to access KVM host 3
+#   hosts: localhost
+#   tags: ssh, ssh_copy_id, section_1, kvm_host_3
+#   connection: local
+#   become: false
+#   gather_facts: false
+#   vars:
+#     ssh_target:
+#       [
+#         " {{ env.systems.host3.ip }}",
+#         "{{ env.systems.host3.user }}",
+#         "{{ env.systems.host3.pass }}",
+#         "{{ path_to_key_pair }}",
+#       ]
+#   tasks:
+#     - name: Include vars for third KVM host
+#       ansible.builtin.include_vars:
+#         file: "{{ inventory_dir }}/host_vars/{{ env.systems.host3.hostname }}.yaml"
+#       when: env.systems.host3.hostname is defined
 
-    - name: copy SSH key to third KVM host, if cluster is to be highly available
-      ansible.builtin.import_role:
-        name: ssh_copy_id
-      when: env.systems.host3.hostname is defined
+#     - name: copy SSH key to third KVM host, if cluster is to be highly available
+#       ansible.builtin.import_role:
+#         name: ssh_copy_id
+#       when: env.systems.host3.hostname is defined
 
 - name: Re-Install cluster - Update ignitions and other install files
   hosts: bastion
   become: true
   pre_tasks:
-    - name: Import initial-resolv.yaml
-      ansible.builtin.import_role:
-        name: dns
-        tasks_from: initial-resolv.yaml
+    # - name: Import initial-resolv.yaml
+    #   ansible.builtin.import_role:
+    #     name: dns
+    #     tasks_from: initial-resolv.yaml
 
-    - name: Check if OCP architecture matches Bastion host architecture
-      ansible.builtin.shell: |
-        set -o pipefail
-        ARCH=$(uname -m | sed 's/aarch64/arm64/;s/x86_64/amd64/')
-        if [[ "${ARCH}" -ne "{{ env.install_config.control.architecture }}" ]]; then
-           echo "ERROR: Install Bastion host with '{{ env.install_config.control.architecture }}' architecture !"
-           exit 1
-        fi
-      changed_when: false
+    # - name: Check if OCP architecture matches Bastion host architecture
+    #   ansible.builtin.shell: |
+    #     set -o pipefail
+    #     ARCH=$(uname -m | sed 's/aarch64/arm64/;s/x86_64/amd64/')
+    #     if [[ "${ARCH}" -ne "{{ env.install_config.control.architecture }}" ]]; then
+    #        echo "ERROR: Install Bastion host with '{{ env.install_config.control.architecture }}' architecture !"
+    #        exit 1
+    #     fi
+    #   changed_when: false
 
   roles:
     - common
-    - get_ocp
     - { role: dns, when: env.bastion.options.dns }
     - { role: haproxy, when: env.bastion.options.loadbalancer.on_bastion }
+    - get_ocp
 
 - import_playbook: 5b_setup_bastion_test_env.yaml
 - import_playbook: 6_create_nodes.yaml
